### ISSUE TITLE
AutomaticallyLevelUpPokemon results in error when set true

### ISSUE THREAD

**Issue by globus243** [PocketMobsters/PokeMobBot#113]
When I set the option `AutomaticallyLevelUpPokemon` to `true`, the programm will eventually crash.
In log i see the message:
```
 [18:16:39] System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei PoGo.PokeMobBot.Logic.Tasks.LevelUpPokemonTask.<Execute>d__0.MoveNext() in C:\Users\Trent\Documents\GitHub\PokeMobBot\PoGo.PokeMobBot.Logic\Tasks\LevelUpPokemonTask.cs:Zeile 39.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   bei PoGo.PokeMobBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\Users\Trent\Documents\GitHub\PokeMobBot\PoGo.PokeMobBot.Logic\State\FarmState.cs:Zeile 26.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   bei PoGo.PokeMobBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\Trent\Documents\GitHub\PokeMobBot\PoGo.PokeMobBot.Logic\State\StateMachine.cs:Zeile 36.
```
The first line translates to `Object reference not set to an instance of an object`

Sometimes the programm first transfers some pokemon and when it's looking which to level up (i suppose) it crashes with the same message and starts all over mostly resulting in the same crash.

**Comment by globus243** [comment]
also. are those pathes `C:\Users\Trent\Documents\GitHub\PokeMobBot\PoGo.PokeMobBot.Logic\State\FarmState.cs:Zeile 26.` really correct? my username is not Trent

**Comment by mvegter197** [comment]
It did upgrade for me without any error, sure you got everything setup properly?

**Comment by globus243** [comment]
I just downloaded the newesr (0.5) release and ran this.

**Comment by mvegter197** [comment]
I'm using the dev version, so I compiled it myself. Might have been fixed but not yet released.

**Comment by globus243** [comment]
would make sense. if you compiled it on your machine, the pathes would be correct. can you run your build with another system?

**Comment by mvegter197** [comment]
@globus243 It still works for me. I will let it run for a extra ~ 15 minutes. As it is currently running on my laptop, which uses a different name, and in a different folder.

**Comment by globus243** [comment]
i compiled it myself the path changed (to my username), but the problem persists.

**Comment by forReason** [comment]
Made a fix, must still be merged. #8

change that in LevelUpPokemonTask.cs:

                var rand = new Random();
                var randomNumber = rand.Next(1, DisplayPokemonStatsTask.PokemonId.Count);

                var upgradeResult =
                    await session.Inventory.UpgradePokemon(DisplayPokemonStatsTask.PokemonId[randomNumber]);
                if (upgradeResult.Result.ToString().ToLower().Contains("success"))
                {
                    Logger.Write("Pokemon Upgraded:" + upgradeResult.UpgradedPokemon.PokemonId + ":" +
                                 upgradeResult.UpgradedPokemon.Cp);
                }
                else if (upgradeResult.Result.ToString().ToLower().Contains("insufficient"))
                {
                    Logger.Write("Pokemon Upgrade Failed Not Enough Resources");
                }
                else if (upgradeResult.UpgradedPokemon != null)
                {
                    Logger.Write(
                        "Pokemon Upgrade Failed Unknown Error, Pokemon Could Be Max Level For Your Level The Pokemon That Caused Issue Was:" +
                        upgradeResult.UpgradedPokemon.PokemonId);
                }

**Comment by UntilSunrise** [comment]
duplication of #84
